# CMake generated Testfile for 
# Source directory: /Users/magneto/Desktop/Codex Playground/Bread
# Build directory: /Users/magneto/Desktop/Codex Playground/Bread/build_codex
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(MazePathfindingTests "/Users/magneto/Desktop/Codex Playground/Bread/build_codex/maze_pathfinding_tests")
set_tests_properties(MazePathfindingTests PROPERTIES  LABELS "smoke;verification;round_trip" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;150;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(ArchiverCompatibilitySmokeTests "/Users/magneto/Desktop/Codex Playground/Bread/build_codex/archiver_compat_smoke_tests")
set_tests_properties(ArchiverCompatibilitySmokeTests PROPERTIES  LABELS "smoke;verification;compatibility" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;168;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(MazePathFinding "/Users/magneto/Desktop/Codex Playground/Bread/build_codex/maze_path_finding")
set_tests_properties(MazePathFinding PROPERTIES  LABELS "regression;verification;quality" RUN_SERIAL "TRUE" WORKING_DIRECTORY "/Users/magneto/Desktop/Codex Playground/Bread" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;186;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(TestMazeGridValidity "/Users/magneto/Desktop/Codex Playground/Bread/build_codex/test_maze_grid_validity")
set_tests_properties(TestMazeGridValidity PROPERTIES  LABELS "regression;verification;quality" RUN_SERIAL "TRUE" WORKING_DIRECTORY "/Users/magneto/Desktop/Codex Playground/Bread" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;208;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(MazeEdgeConnectedQuick "/Users/magneto/Desktop/Codex Playground/Bread/build_codex/maze_edge_connected_quick")
set_tests_properties(MazeEdgeConnectedQuick PROPERTIES  LABELS "regression;verification;quality" RUN_SERIAL "TRUE" WORKING_DIRECTORY "/Users/magneto/Desktop/Codex Playground/Bread" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;230;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(MazeEdgeConnectedPrimQuick "/Users/magneto/Desktop/Codex Playground/Bread/build_codex/maze_edge_connected_prim_quick")
set_tests_properties(MazeEdgeConnectedPrimQuick PROPERTIES  LABELS "regression;verification;quality" RUN_SERIAL "TRUE" WORKING_DIRECTORY "/Users/magneto/Desktop/Codex Playground/Bread" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;252;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(MazeEdgeConnectedKruskalQuick "/Users/magneto/Desktop/Codex Playground/Bread/build_codex/maze_edge_connected_kruskal_quick")
set_tests_properties(MazeEdgeConnectedKruskalQuick PROPERTIES  LABELS "regression;verification;quality" RUN_SERIAL "TRUE" WORKING_DIRECTORY "/Users/magneto/Desktop/Codex Playground/Bread" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;274;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(GameRepeatabilityTests "/Users/magneto/Desktop/Codex Playground/Bread/build_codex/game_repeatability_tests")
set_tests_properties(GameRepeatabilityTests PROPERTIES  LABELS "regression;verification;repeatability" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;347;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(CounterRepeatabilityTests "/Users/magneto/Desktop/Codex Playground/Bread/build_codex/counter_repeatability_tests")
set_tests_properties(CounterRepeatabilityTests PROPERTIES  LABELS "regression;verification;repeatability" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;365;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(FastRandRepeatabilityTests "/Users/magneto/Desktop/Codex Playground/Bread/build_codex/fast_rand_repeatability_tests")
set_tests_properties(FastRandRepeatabilityTests PROPERTIES  LABELS "regression;verification;repeatability" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;383;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(ByteTwisterPoisonRepeatabilityTests "/Users/magneto/Desktop/Codex Playground/Bread/build_codex/byte_twister_poison_repeatability_tests")
set_tests_properties(ByteTwisterPoisonRepeatabilityTests PROPERTIES  LABELS "regression;verification;repeatability" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;401;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(DigestRepeatabilitySuite "/Users/magneto/Desktop/Codex Playground/Bread/build_codex/digest_repeatability_suite")
set_tests_properties(DigestRepeatabilitySuite PROPERTIES  LABELS "regression;verification;repeatability" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;474;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(TestPasswordExpander "/Users/magneto/Desktop/Codex Playground/Bread/build_codex/test_password_expander")
set_tests_properties(TestPasswordExpander PROPERTIES  LABELS "smoke;verification;repeatability" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;492;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(TestAllScramblers "/Users/magneto/Desktop/Codex Playground/Bread/build_codex/TestAllScramblers" "10" "/Users/magneto/Desktop/Codex Playground/Bread/build_codex/TestAllScramblers_report.html")
set_tests_properties(TestAllScramblers PROPERTIES  LABELS "regression;verification;scramblers" WORKING_DIRECTORY "/Users/magneto/Desktop/Codex Playground/Bread/build_codex" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;510;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(PasswordExpanderQualityReport "/Users/magneto/Desktop/Codex Playground/Bread/build_codex/password_expander_quality_report" "2" "hotdog" "password_expander_quality_report.html")
set_tests_properties(PasswordExpanderQualityReport PROPERTIES  LABELS "regression;verification;quality" WORKING_DIRECTORY "/Users/magneto/Desktop/Codex Playground/Bread/build_codex" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;518;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(PasswordExpanderConfusionMatrix "/Users/magneto/Desktop/Codex Playground/Bread/build_codex/password_expander_confusion_matrix" "2" "hotdog" "password_expander_confusion_matrix.html")
set_tests_properties(PasswordExpanderConfusionMatrix PROPERTIES  LABELS "regression;verification;quality" WORKING_DIRECTORY "/Users/magneto/Desktop/Codex Playground/Bread/build_codex" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;527;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(GamePerseveranceTests "/Users/magneto/Desktop/Codex Playground/Bread/build_codex/game_perseverance_tests")
set_tests_properties(GamePerseveranceTests PROPERTIES  LABELS "regression;verification;perseverance" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;552;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(MazePerseveranceTests "/Users/magneto/Desktop/Codex Playground/Bread/build_codex/maze_perseverance_tests")
set_tests_properties(MazePerseveranceTests PROPERTIES  LABELS "regression;verification;perseverance" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;570;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(MazeStabilityTests "/Users/magneto/Desktop/Codex Playground/Bread/build_codex/maze_stability_tests" "2")
set_tests_properties(MazeStabilityTests PROPERTIES  LABELS "regression;verification;stability" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;588;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
