# CMake generated Testfile for 
# Source directory: /Users/magneto/Desktop/Codex Playground/Bread
# Build directory: /Users/magneto/Desktop/Codex Playground/Bread/build_release
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(FastMatrixRoundTripTests "/Users/magneto/Desktop/Codex Playground/Bread/build_release/fast_matrix_round_trip_tests")
set_tests_properties(FastMatrixRoundTripTests PROPERTIES  LABELS "smoke;verification;round_trip" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;81;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(MazePathfindingTests "/Users/magneto/Desktop/Codex Playground/Bread/build_release/maze_pathfinding_tests")
set_tests_properties(MazePathfindingTests PROPERTIES  LABELS "smoke;verification;round_trip" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;99;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(MazePathFinding "/Users/magneto/Desktop/Codex Playground/Bread/build_release/maze_path_finding")
set_tests_properties(MazePathFinding PROPERTIES  LABELS "regression;verification;quality" RUN_SERIAL "TRUE" WORKING_DIRECTORY "/Users/magneto/Desktop/Codex Playground/Bread" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;117;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(TestMazeGridValidity "/Users/magneto/Desktop/Codex Playground/Bread/build_release/test_maze_grid_validity")
set_tests_properties(TestMazeGridValidity PROPERTIES  LABELS "regression;verification;quality" RUN_SERIAL "TRUE" WORKING_DIRECTORY "/Users/magneto/Desktop/Codex Playground/Bread" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;139;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(MazeEdgeConnectedQuick "/Users/magneto/Desktop/Codex Playground/Bread/build_release/maze_edge_connected_quick")
set_tests_properties(MazeEdgeConnectedQuick PROPERTIES  LABELS "regression;verification;quality" RUN_SERIAL "TRUE" WORKING_DIRECTORY "/Users/magneto/Desktop/Codex Playground/Bread" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;161;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(MazeEdgeConnectedPrimQuick "/Users/magneto/Desktop/Codex Playground/Bread/build_release/maze_edge_connected_prim_quick")
set_tests_properties(MazeEdgeConnectedPrimQuick PROPERTIES  LABELS "regression;verification;quality" RUN_SERIAL "TRUE" WORKING_DIRECTORY "/Users/magneto/Desktop/Codex Playground/Bread" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;183;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(MazeEdgeConnectedKruskalQuick "/Users/magneto/Desktop/Codex Playground/Bread/build_release/maze_edge_connected_kruskal_quick")
set_tests_properties(MazeEdgeConnectedKruskalQuick PROPERTIES  LABELS "regression;verification;quality" RUN_SERIAL "TRUE" WORKING_DIRECTORY "/Users/magneto/Desktop/Codex Playground/Bread" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;205;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(GameRepeatabilityTests "/Users/magneto/Desktop/Codex Playground/Bread/build_release/game_repeatability_tests")
set_tests_properties(GameRepeatabilityTests PROPERTIES  LABELS "regression;verification;repeatability" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;278;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(CounterRepeatabilityTests "/Users/magneto/Desktop/Codex Playground/Bread/build_release/counter_repeatability_tests")
set_tests_properties(CounterRepeatabilityTests PROPERTIES  LABELS "regression;verification;repeatability" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;296;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(FastRandRepeatabilityTests "/Users/magneto/Desktop/Codex Playground/Bread/build_release/fast_rand_repeatability_tests")
set_tests_properties(FastRandRepeatabilityTests PROPERTIES  LABELS "regression;verification;repeatability" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;314;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(ByteTwisterPoisonRepeatabilityTests "/Users/magneto/Desktop/Codex Playground/Bread/build_release/byte_twister_poison_repeatability_tests")
set_tests_properties(ByteTwisterPoisonRepeatabilityTests PROPERTIES  LABELS "regression;verification;repeatability" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;332;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(DigestRepeatabilitySuite "/Users/magneto/Desktop/Codex Playground/Bread/build_release/digest_repeatability_suite")
set_tests_properties(DigestRepeatabilitySuite PROPERTIES  LABELS "regression;verification;repeatability" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;371;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(TestPasswordExpander "/Users/magneto/Desktop/Codex Playground/Bread/build_release/test_password_expander")
set_tests_properties(TestPasswordExpander PROPERTIES  LABELS "smoke;verification;repeatability" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;389;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(PasswordExpanderQualityReport "/Users/magneto/Desktop/Codex Playground/Bread/build_release/password_expander_quality_report" "2" "hotdog" "password_expander_quality_report.html")
set_tests_properties(PasswordExpanderQualityReport PROPERTIES  LABELS "regression;verification;quality" WORKING_DIRECTORY "/Users/magneto/Desktop/Codex Playground/Bread/build_release" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;392;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(PasswordExpanderConfusionMatrix "/Users/magneto/Desktop/Codex Playground/Bread/build_release/password_expander_confusion_matrix" "2" "hotdog" "password_expander_confusion_matrix.html")
set_tests_properties(PasswordExpanderConfusionMatrix PROPERTIES  LABELS "regression;verification;quality" WORKING_DIRECTORY "/Users/magneto/Desktop/Codex Playground/Bread/build_release" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;401;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(GamePerseveranceTests "/Users/magneto/Desktop/Codex Playground/Bread/build_release/game_perseverance_tests")
set_tests_properties(GamePerseveranceTests PROPERTIES  LABELS "regression;verification;perseverance" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;426;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(MazePerseveranceTests "/Users/magneto/Desktop/Codex Playground/Bread/build_release/maze_perseverance_tests")
set_tests_properties(MazePerseveranceTests PROPERTIES  LABELS "regression;verification;perseverance" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;444;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
add_test(MazeStabilityTests "/Users/magneto/Desktop/Codex Playground/Bread/build_release/maze_stability_tests" "2")
set_tests_properties(MazeStabilityTests PROPERTIES  LABELS "regression;verification;stability" _BACKTRACE_TRIPLES "/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;462;add_test;/Users/magneto/Desktop/Codex Playground/Bread/CMakeLists.txt;0;")
